name: Release CorrelationTracking NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.*

    - name: Dotnet restore
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore

    - name: Publish CorrelationTracking
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: /src/CorrelationTracking.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}